// GENERATED by scripts/bundle_snack.sh -- do not edit.
// Source of truth is app/App.js and app/src/. Regenerate after any change.

// app/App.js
import React9, { useCallback, useEffect, useMemo as useMemo5, useRef as useRef2, useState as useState7 } from "react";
import { Pressable as Pressable5, SafeAreaView, StatusBar, StyleSheet as StyleSheet8, Text as Text8, View as View8 } from "react-native";

// app/src/components/UI.js
import React, { useState } from "react";
import {
  ActivityIndicator,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View
} from "react-native";

// app/src/components/svg.js
import {
  default as Default,
  Circle,
  Defs,
  Line,
  LinearGradient,
  Path,
  Polyline,
  Rect,
  Stop
} from "react-native-svg";

// app/src/haptics.js
import * as Haptics from "expo-haptics";
var enabled = true;
var setHapticsEnabled = (value) => {
  enabled = !!value;
};
var fire = (fn) => {
  if (!enabled) return;
  try {
    const result = fn();
    if (result && typeof result.catch === "function") result.catch(() => {
    });
  } catch (err) {
  }
};
var tick = () => fire(() => Haptics.selectionAsync());
var tap = () => fire(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
var confirm = () => fire(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
var undo = () => fire(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));

// app/src/theme.js
import { Platform } from "react-native";
var C = {
  bg: "#0A0B0C",
  surface: "#141518",
  surfaceHi: "#1C1E22",
  line: "#2A2D32",
  lineSoft: "#1F2226",
  // Secondary text was too dim to carry the weight it was being given. `dim`
  // clears 7:1 on the page background and `faint` clears 4.5:1, so a label at
  // the smallest size in use is still comfortably readable rather than merely
  // present.
  text: "#F0F1F2",
  dim: "#B6BCC4",
  faint: "#8A9098",
  acid: "#C8FF00",
  acidDim: "#A6D400",
  acidGlow: "rgba(200,255,0,0.10)",
  up: "#C8FF00",
  down: "#FF6B4F",
  flat: "#8A9098"
};
var MONO = Platform.select({
  ios: "Menlo",
  android: "monospace",
  default: "monospace"
});
var T = {
  micro: 11,
  small: 12,
  body: 13,
  large: 15,
  title: 20,
  display: 34
};
var S = {
  gutter: 16,
  radius: 10,
  hairline: 1,
  // Apple's minimum comfortable target. Visible pills stay small; the touchable
  // area around them does not.
  tap: 44
};
var slop = (size) => {
  const pad = Math.max(0, Math.round((S.tap - size) / 2));
  return { top: pad, bottom: pad, left: pad, right: pad };
};
var tone = (value) => {
  if (value === null || value === void 0 || value === 0) return C.flat;
  return value > 0 ? C.up : C.down;
};
var fmtCap = (n) => {
  if (!n && n !== 0) return "\u2014";
  if (n >= 1e12) return `${(n / 1e12).toFixed(2)}T`;
  if (n >= 1e9) return `${(n / 1e9).toFixed(1)}B`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(0)}M`;
  return `${n}`;
};
var fmtPrice = (n) => {
  if (n === null || n === void 0) return "\u2014";
  if (n >= 1e4) return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};
var fmtPct = (n, digits = 2) => {
  if (n === null || n === void 0) return "\u2014";
  return `${n >= 0 ? "+" : ""}${n.toFixed(digits)}%`;
};
var fmtMagnitude = (n, digits = 1) => n === null || n === void 0 ? "\u2014" : `${n.toFixed(digits)}%`;
var fmtNum = (n, digits = 2) => n === null || n === void 0 ? "\u2014" : n.toFixed(digits);
var fmtRank = (n) => n === null || n === void 0 ? "\u2014" : `#${n}`;
var fmtWhen = (iso) => {
  if (!iso) return "\u2014";
  const then = new Date(iso);
  if (Number.isNaN(then.getTime())) return "\u2014";
  const mins = Math.floor((Date.now() - then.getTime()) / 6e4);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
};
var missingReason = (key) => {
  switch (key) {
    case "momentum":
      return "Needs ~13 months";
    case "2y":
      return "Needs 2 years";
    case "1y":
    case "riskAdjusted":
    case "maxDrawdown":
      return "Needs 1 year";
    case "9m":
      return "Needs 9 months";
    case "6m":
    case "90d":
      return "Needs 6 months";
    case "3m":
      return "Needs 3 months";
    case "ytd":
      return "Listed this year";
    default:
      return "Not enough history";
  }
};

// app/src/components/UI.js
function ChipRow({ children, accessibilityLabel }) {
  const [overflow, setOverflow] = useState(false);
  const [atEnd, setAtEnd] = useState(false);
  const [width, setWidth] = useState(0);
  return <View style={styles.chipRowWrap}>
      <ScrollView
    horizontal
    showsHorizontalScrollIndicator={false}
    style={styles.chipRow}
    contentContainerStyle={styles.chipRowContent}
    accessibilityLabel={accessibilityLabel}
    onLayout={(e) => setWidth(e.nativeEvent.layout.width)}
    onContentSizeChange={(w) => setOverflow(w > width + 1)}
    onScroll={(e) => {
      const { contentOffset, contentSize, layoutMeasurement } = e.nativeEvent;
      setAtEnd(contentOffset.x + layoutMeasurement.width >= contentSize.width - 2);
    }}
    scrollEventThrottle={32}
  >
        {children}
      </ScrollView>

      {overflow && !atEnd && <View pointerEvents="none" style={styles.fade}>
          <Default width={36} height="100%">
            <Defs>
              <LinearGradient id="chipFade" x1="0" y1="0" x2="1" y2="0">
                <Stop offset="0" stopColor={C.bg} stopOpacity="0" />
                <Stop offset="1" stopColor={C.bg} stopOpacity="1" />
              </LinearGradient>
            </Defs>
            <Rect x="0" y="0" width="36" height="100%" fill="url(#chipFade)" />
          </Default>
          <Text style={styles.fadeMark}>›</Text>
        </View>}
    </View>;
}
function Chip({ label, active, onPress, compact, accessibilityLabel }) {
  return <Pressable
    onPress={() => {
      tick();
      onPress();
    }}
    hitSlop={slop(compact ? 30 : 34)}
    accessibilityRole="button"
    accessibilityState={{ selected: !!active }}
    accessibilityLabel={accessibilityLabel || label}
    style={({ pressed }) => [
      styles.chip,
      compact && styles.chipCompact,
      active && styles.chipActive,
      pressed && !active && styles.chipPressed
    ]}
  >
      <Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text>
    </Pressable>;
}
function Stat({ label, value, color, width = "33.33%", reason }) {
  const blank = value === "\u2014" || value === null || value === void 0;
  return <View style={[styles.stat, { width }]}>
      <Text style={styles.statLabel}>{label}</Text>
      {blank && reason ? <Text style={styles.statReason}>{reason}</Text> : <Text style={[styles.statValue, color && { color }]}>{value}</Text>}
    </View>;
}
function Disclosure({ label, children }) {
  const [open, setOpen] = useState(false);
  return <View style={styles.disclosure}>
      <Pressable
    onPress={() => {
      tick();
      setOpen((wasOpen) => !wasOpen);
    }}
    accessibilityRole="button"
    accessibilityState={{ expanded: open }}
    style={({ pressed }) => [styles.disclosureRow, pressed && styles.disclosurePressed]}
  >
        <Text style={styles.disclosureLabel}>{label}</Text>
        <Text style={styles.disclosureMark}>{open ? "\u2304" : "\u203A"}</Text>
      </Pressable>
      {open && <View style={styles.disclosureBody}>{children}</View>}
    </View>;
}
function SelectSheet({ title, hint, options, value, visible, onSelect, onClose }) {
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <Pressable style={styles.sheetBackdrop} onPress={onClose} accessibilityLabel="Dismiss">
        {
    /* The inner press is swallowed so tapping the sheet itself does not
       dismiss it; only the backdrop does. */
  }
        <Pressable style={styles.sheet} onPress={() => {
  }}>
          <Text style={styles.sheetTitle}>{title}</Text>
          {!!hint && <Text style={styles.sheetHint}>{hint}</Text>}
          <ScrollView bounces={false}>
            {options.map((option) => {
    const active = option.value === value;
    return <Pressable
      key={option.value}
      onPress={() => {
        tick();
        onSelect(option.value);
        onClose();
      }}
      accessibilityRole="button"
      accessibilityState={{ selected: active }}
      accessibilityLabel={`${option.label}${option.count === void 0 ? "" : `, ${option.count}`}` + (active ? ", selected" : "")}
      style={({ pressed }) => [styles.sheetRow, pressed && styles.sheetRowPressed]}
    >
                  <Text style={[styles.sheetLabel, active && styles.sheetLabelActive]}>
                    {option.label}
                  </Text>
                  <Text style={[styles.sheetCount, active && styles.sheetLabelActive]}>
                    {option.count === void 0 ? active ? "\u2713" : "" : active ? `${option.count}  \u2713` : option.count}
                  </Text>
                </Pressable>;
  })}
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>;
}
function SelectButton({ label, active, onPress, accessibilityLabel }) {
  return <Pressable
    onPress={() => {
      tick();
      onPress();
    }}
    accessibilityRole="button"
    accessibilityLabel={accessibilityLabel || label}
    style={({ pressed }) => [
      styles.select,
      active && styles.selectActive,
      pressed && styles.selectPressed
    ]}
  >
      <Text numberOfLines={1} style={[styles.selectText, active && styles.selectTextActive]}>
        {label}
      </Text>
      <Text style={[styles.selectMark, active && styles.selectTextActive]}>▾</Text>
    </Pressable>;
}
function ActionButton({ label, onPress, busy, tone: kind = "normal" }) {
  return <Pressable
    onPress={busy ? void 0 : () => {
      tick();
      onPress();
    }}
    disabled={busy}
    accessibilityRole="button"
    accessibilityState={{ disabled: !!busy, busy: !!busy }}
    style={({ pressed }) => [
      styles.action,
      kind === "danger" && styles.actionDanger,
      busy && styles.actionBusy,
      pressed && !busy && styles.actionPressed
    ]}
  >
      <Text style={[styles.actionText, kind === "danger" && styles.actionTextDanger, busy && styles.actionTextBusy]}>
        {label}
      </Text>
    </Pressable>;
}
function SectionTitle({ children, right }) {
  return <View style={styles.sectionRow}>
      <Text style={styles.section} accessibilityRole="header">{children}</Text>
      {right}
    </View>;
}
function Banner({ text, tone: kind = "warn" }) {
  return <View style={[styles.banner, kind === "error" && styles.bannerError, kind === "ok" && styles.bannerOk]}>
      <Text style={[styles.bannerText, kind === "error" && styles.bannerTextError]}>{text}</Text>
    </View>;
}
function Snackbar({ text, actionLabel, onAction }) {
  return <View style={styles.snack} accessibilityLiveRegion="polite">
      <Text style={styles.snackText} numberOfLines={2}>{text}</Text>
      {!!actionLabel && <Pressable onPress={onAction} hitSlop={slop(28)} accessibilityRole="button">
          <Text style={styles.snackAction}>{actionLabel}</Text>
        </Pressable>}
    </View>;
}
function Loading({ label = "LOADING" }) {
  return <View style={styles.loading}>
      <ActivityIndicator color={C.acid} />
      <Text style={styles.loadingText}>{label}</Text>
    </View>;
}
function Empty({ title, hint }) {
  return <View style={styles.empty}>
      <Text style={styles.emptyTitle}>{title}</Text>
      {!!hint && <Text style={styles.emptyHint}>{hint}</Text>}
    </View>;
}
var styles = StyleSheet.create({
  chipRowWrap: { position: "relative" },
  chipRow: { flexGrow: 0, flexShrink: 0, marginBottom: 8 },
  chipRowContent: { paddingHorizontal: S.gutter, alignItems: "center", paddingVertical: 4 },
  fade: { position: "absolute", right: 0, top: 0, bottom: 8, width: 36, justifyContent: "center", alignItems: "flex-end" },
  fadeMark: { position: "absolute", right: 3, color: C.dim, fontFamily: MONO, fontSize: T.body },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 7,
    borderWidth: S.hairline,
    borderColor: C.line,
    backgroundColor: C.surface,
    marginRight: 7
  },
  chipCompact: { paddingHorizontal: 10, paddingVertical: 7 },
  chipPressed: { borderColor: C.faint },
  chipActive: { backgroundColor: C.acid, borderColor: C.acid },
  chipText: { color: C.dim, fontFamily: MONO, fontSize: T.micro, lineHeight: T.micro + 3, letterSpacing: 0.8 },
  chipTextActive: { color: C.bg },
  select: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: S.radius,
    borderWidth: S.hairline,
    borderColor: C.line,
    backgroundColor: C.surface,
    maxWidth: 158
  },
  selectActive: { borderColor: C.acid },
  selectPressed: { borderColor: C.faint },
  selectText: { color: C.dim, fontFamily: MONO, fontSize: T.micro, lineHeight: T.micro + 3, letterSpacing: 0.6, flexShrink: 1 },
  selectTextActive: { color: C.acid },
  selectMark: { color: C.faint, fontFamily: MONO, fontSize: T.micro, marginLeft: 6 },
  action: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 7,
    borderWidth: S.hairline,
    borderColor: C.acid,
    marginRight: 8,
    marginTop: 8
  },
  actionDanger: { borderColor: C.down },
  actionPressed: { backgroundColor: C.acidGlow },
  actionBusy: { borderColor: C.line },
  actionText: { color: C.acid, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1 },
  actionTextDanger: { color: C.down },
  actionTextBusy: { color: C.faint },
  sheetBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.72)", justifyContent: "flex-end" },
  sheet: {
    backgroundColor: C.surface,
    borderTopWidth: S.hairline,
    borderTopColor: C.line,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    paddingTop: 16,
    paddingBottom: 28,
    maxHeight: "72%"
  },
  sheetTitle: {
    color: C.dim,
    fontFamily: MONO,
    fontSize: T.micro,
    letterSpacing: 1.4,
    paddingHorizontal: S.gutter,
    paddingBottom: 10
  },
  sheetHint: {
    color: C.faint,
    fontSize: T.micro,
    lineHeight: T.micro + 6,
    paddingHorizontal: S.gutter,
    paddingBottom: 12
  },
  sheetRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: S.gutter,
    minHeight: S.tap,
    paddingVertical: 12,
    borderTopWidth: S.hairline,
    borderTopColor: C.lineSoft
  },
  sheetRowPressed: { backgroundColor: C.surfaceHi },
  sheetLabel: { color: C.text, fontFamily: MONO, fontSize: T.body, letterSpacing: 0.4, flexShrink: 1 },
  sheetLabelActive: { color: C.acid },
  sheetCount: { color: C.dim, fontFamily: MONO, fontSize: T.small, marginLeft: 12 },
  disclosure: { marginTop: 18, borderTopWidth: S.hairline, borderTopColor: C.line },
  disclosureRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: S.tap,
    paddingVertical: 12
  },
  disclosurePressed: { opacity: 0.6 },
  disclosureLabel: { color: C.dim, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1.3 },
  disclosureMark: { color: C.acid, fontFamily: MONO, fontSize: T.large },
  disclosureBody: { paddingBottom: 14 },
  stat: { paddingVertical: 10, paddingRight: 10 },
  statLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.6 },
  statValue: { color: C.text, fontFamily: MONO, fontSize: T.large, marginTop: 4 },
  statReason: { color: C.faint, fontSize: T.micro, marginTop: 5, fontStyle: "italic" },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 2
  },
  section: { color: C.dim, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1.5 },
  banner: {
    backgroundColor: C.acidGlow,
    borderLeftWidth: 2,
    borderLeftColor: C.acid,
    paddingVertical: 9,
    paddingHorizontal: 11,
    marginHorizontal: S.gutter,
    marginBottom: 8,
    borderRadius: 4
  },
  bannerError: { backgroundColor: "rgba(255,107,79,0.12)", borderLeftColor: C.down },
  bannerOk: { backgroundColor: "rgba(200,255,0,0.08)" },
  bannerText: { color: C.dim, fontFamily: MONO, fontSize: T.micro, lineHeight: T.micro + 5 },
  bannerTextError: { color: C.down },
  snack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: C.surfaceHi,
    borderWidth: S.hairline,
    borderColor: C.line,
    borderRadius: S.radius,
    marginHorizontal: S.gutter,
    marginBottom: 8,
    paddingHorizontal: 14,
    minHeight: S.tap
  },
  snackText: { color: C.text, fontSize: T.small, flexShrink: 1, paddingVertical: 10 },
  snackAction: { color: C.acid, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1, paddingLeft: 14 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { color: C.dim, fontFamily: MONO, fontSize: T.micro, letterSpacing: 2, marginTop: 12 },
  empty: { alignItems: "center", justifyContent: "center", paddingTop: 70, paddingHorizontal: 30 },
  emptyTitle: { color: C.dim, fontFamily: MONO, fontSize: T.body, letterSpacing: 1 },
  emptyHint: { color: C.faint, fontSize: T.small, marginTop: 10, textAlign: "center", lineHeight: 19 }
});

// app/src/storage.js
import AsyncStorage from "@react-native-async-storage/async-storage";

// app/src/source.js
var DEFAULT_SOURCE = "https://raw.githubusercontent.com/vandyckmed-droid/thisone/main/data/";
var normaliseBase = (url) => {
  const trimmed = (url || "").trim();
  const withoutFile = trimmed.replace(/(index|snapshot)\.json$/i, "");
  return withoutFile.endsWith("/") ? withoutFile : `${withoutFile}/`;
};

// app/src/storage.js
var K = {
  watchlist: "@top100/watchlist",
  settings: "@top100/settings",
  index: "@top100/index",
  // Each universe caches under its own key, so switching between them is
  // instant after the first visit and every one of them survives going offline.
  universe: (key) => `@top100/universe/${key}`
};
var DEFAULT_SETTINGS = {
  sourceUrl: DEFAULT_SOURCE,
  universeKey: "all",
  defaultSort: "marketCap",
  showLogos: true,
  showSparklines: true,
  refreshOnOpen: true,
  haptics: true,
  // Flipped the first time a chart is scrubbed, so the hint appears once.
  hasScrubbed: false
};
var read = async (key, fallback) => {
  try {
    const raw = await AsyncStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch (err) {
    return fallback;
  }
};
var write = async (key, value) => {
  try {
    await AsyncStorage.setItem(key, JSON.stringify(value));
    return true;
  } catch (err) {
    return false;
  }
};
var loadWatchlist = () => read(K.watchlist, []);
var saveWatchlist = (symbols) => write(K.watchlist, symbols);
var loadSettings = async () => ({
  ...DEFAULT_SETTINGS,
  ...await read(K.settings, {})
});
var saveSettings = (settings) => write(K.settings, settings);
var loadCachedIndex = () => read(K.index, null);
var saveCachedIndex = (index) => write(K.index, index);
var loadCachedUniverse = (key) => read(K.universe(key), null);
var saveCachedUniverse = (key, table) => write(K.universe(key), table);
var clearAll = async () => {
  try {
    const keys = await AsyncStorage.getAllKeys();
    await AsyncStorage.multiRemove(keys.filter((k) => k.startsWith("@top100/")));
    return true;
  } catch (err) {
    return false;
  }
};

// app/src/data.js
var SORTS = [
  { key: "marketCap", label: "MKT CAP", short: "CAP", rank: "marketCap", better: "high", value: (t) => t.marketCap, format: "cap" },
  { key: "change", label: "1 DAY", short: "1D", rank: "change", better: "high", value: (t) => t.changePct, format: "pct" },
  { key: "r1w", label: "1 WEEK", short: "1W", rank: "return_1w", better: "high", value: (t) => t.returns["1w"], format: "pct" },
  { key: "r1m", label: "1 MONTH", short: "1M", rank: "return_1m", better: "high", value: (t) => t.returns["1m"], format: "pct" },
  { key: "r3m", label: "3 MONTH", short: "3M", rank: "return_3m", better: "high", value: (t) => t.returns["3m"], format: "pct" },
  { key: "r6m", label: "6 MONTH", short: "6M", rank: "return_6m", better: "high", value: (t) => t.returns["6m"], format: "pct" },
  { key: "r1y", label: "1 YEAR", short: "1Y", rank: "return_1y", better: "high", value: (t) => t.returns["1y"], format: "pct" },
  { key: "momentum", label: "MOMENTUM", short: "MOM", rank: "momentum", better: "high", value: (t) => t.momentumScore, format: "score" },
  { key: "risk", label: "RISK-ADJ", short: "R/R", rank: "riskAdjusted", better: "high", value: (t) => t.riskAdjusted1y, format: "ratio" },
  { key: "vol", label: "VOLATILITY", short: "VOL", rank: "volatility", better: "low", value: (t) => t.volatility["1y"], format: "pct0" }
];
var sortByKey = (key) => SORTS.find((s) => s.key === key) || SORTS[0];
var RANGES = [
  { key: "1M", sessions: 21 },
  { key: "3M", sessions: 63 },
  { key: "6M", sessions: 126 },
  { key: "9M", sessions: 189 },
  { key: "1Y", sessions: 252 },
  { key: "2Y", sessions: 504 },
  { key: "MAX", sessions: Infinity }
];
var bust = (url) => `${url}${url.includes("?") ? "&" : "?"}t=${Date.now()}`;
async function getJson(url) {
  const res = await fetch(bust(url), { headers: { "Cache-Control": "no-cache" } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}
async function fetchIndex(sourceUrl) {
  const base = normaliseBase(sourceUrl);
  try {
    const index = await getJson(`${base}index.json`);
    if (!index || !Array.isArray(index.universes) || !index.universes.length) {
      throw new Error("Index is empty or malformed");
    }
    await saveCachedIndex(index);
    return { index, fromCache: false, error: null };
  } catch (err) {
    const cached = await loadCachedIndex();
    if (cached) return { index: cached, fromCache: true, error: err.message };
    return {
      index: { universes: [{ key: "all", title: "All", scope: "all", file: "snapshot.json" }] },
      fromCache: false,
      error: err.message
    };
  }
}
async function fetchUniverse(sourceUrl, universe) {
  const base = normaliseBase(sourceUrl);
  const key = universe.key;
  try {
    const fetched = await getJson(`${base}${universe.file}`);
    if (!fetched || !Array.isArray(fetched.tickers) || !fetched.tickers.length) {
      throw new Error("Table is empty or malformed");
    }
    const table = {
      title: universe.title || universe.key,
      scope: universe.scope || "all",
      ...fetched,
      universeSize: fetched.universeSize || fetched.tickers.length
    };
    await saveCachedUniverse(key, table);
    return { table, fromCache: false, error: null, fetchedAt: Date.now() };
  } catch (err) {
    const cached = await loadCachedUniverse(key);
    if (cached) return { table: cached, fromCache: true, error: err.message, fetchedAt: null };
    throw err;
  }
}
function universeLabel(table) {
  if (!table) return "";
  return table.scope === "sector" ? `${table.title.toUpperCase()} ${table.universeSize}` : `TOP ${table.universeSize}`;
}
function describeUniverse(table) {
  if (!table) return "";
  return table.scope === "sector" ? `${table.universeSize} LARGEST ${table.title.toUpperCase()} COMPANIES` : `${table.universeSize} LARGEST US COMPANIES`;
}
function universeOptions(index) {
  if (!index || !Array.isArray(index.universes)) return [];
  return index.universes.map((u) => ({
    value: u.key,
    label: u.title.toUpperCase(),
    count: u.size
  }));
}
var findUniverse = (index, key) => {
  const list = index && index.universes || [];
  return list.find((u) => u.key === key) || list[0] || null;
};
function arrange(tickers, { sortKey, query, sector, industry, direction = "desc" }) {
  const sort = sortByKey(sortKey);
  const needle = (query || "").trim().toLowerCase();
  let rows = tickers;
  if (needle) {
    rows = rows.filter(
      (t) => t.symbol.toLowerCase().includes(needle) || t.name.toLowerCase().includes(needle)
    );
  }
  if (sector && sector !== "All") {
    rows = rows.filter((t) => t.sector === sector);
  }
  if (industry && industry !== "All") {
    rows = rows.filter((t) => t.industry === industry);
  }
  const bestIsHigh = sort.better === "high";
  const descending = direction === "desc" ? bestIsHigh : !bestIsHigh;
  return [...rows].sort((a, b) => {
    const av = sort.value(a);
    const bv = sort.value(b);
    const aMissing = av === null || av === void 0;
    const bMissing = bv === null || bv === void 0;
    if (aMissing && bMissing) return a.marketCap > b.marketCap ? -1 : 1;
    if (aMissing) return 1;
    if (bMissing) return -1;
    return descending ? bv - av : av - bv;
  });
}
function sortOptions() {
  return SORTS.map((s) => ({ value: s.key, label: s.label }));
}
function groupOptions(tickers, field, allLabel) {
  const counts = /* @__PURE__ */ new Map();
  for (const ticker of tickers) {
    const value = ticker[field];
    if (!value) continue;
    counts.set(value, (counts.get(value) || 0) + 1);
  }
  return [
    { value: "All", label: allLabel, count: tickers.length },
    ...Array.from(counts.entries()).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([name, count]) => ({ value: name, label: name.toUpperCase(), count }))
  ];
}
var sectorOptions = (tickers) => groupOptions(tickers, "sector", "ALL SECTORS");
var industryOptions = (tickers) => groupOptions(tickers, "industry", "ALL INDUSTRIES");
function seriesFor(ticker, dates, sessions) {
  const points = [];
  for (let i = 0; i < ticker.history.length; i += 1) {
    const close = ticker.history[i];
    if (close !== null && close !== void 0) {
      points.push({ date: dates[i], close });
    }
  }
  if (!Number.isFinite(sessions) || points.length <= sessions) return points;
  return points.slice(points.length - sessions);
}
function downsample(points, count) {
  if (points.length <= count) return points;
  const step = (points.length - 1) / (count - 1);
  const out = [];
  for (let i = 0; i < count; i += 1) {
    out.push(points[Math.round(i * step)]);
  }
  return out;
}
function changeOver(points) {
  if (points.length < 2) return null;
  const first = points[0].close;
  const last = points[points.length - 1].close;
  if (!first) return null;
  return (last / first - 1) * 100;
}

// app/src/screens/RanksScreen.js
import React4, { useMemo, useState as useState3 } from "react";
import {
  ActivityIndicator as ActivityIndicator2,
  FlatList,
  Pressable as Pressable3,
  RefreshControl,
  StyleSheet as StyleSheet3,
  Text as Text3,
  TextInput,
  View as View3
} from "react-native";

// app/src/components/TickerRow.js
import React3, { useState as useState2 } from "react";
import { Image, Pressable as Pressable2, StyleSheet as StyleSheet2, Text as Text2, View as View2 } from "react-native";

// app/src/components/Sparkline.js
import React2 from "react";
function Sparkline({ points, width = 56, height = 22, color = C.acid }) {
  if (!points || points.length < 2) {
    return <Default width={width} height={height} />;
  }
  let min = Infinity;
  let max = -Infinity;
  for (const p of points) {
    if (p.close < min) min = p.close;
    if (p.close > max) max = p.close;
  }
  const span = max - min || 1;
  const pad = 2;
  const usable = height - pad * 2;
  const step = width / (points.length - 1);
  const coords = points.map((p, i) => {
    const x = i * step;
    const y = pad + usable - (p.close - min) / span * usable;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  return <Default width={width} height={height}>
      <Polyline
    points={coords}
    fill="none"
    stroke={color}
    strokeWidth={1.4}
    strokeLinejoin="round"
    strokeLinecap="round"
  />
    </Default>;
}
var Sparkline_default = React2.memo(Sparkline);

// app/src/components/TickerRow.js
var formatMetric = (format, value) => {
  switch (format) {
    case "cap":
      return fmtCap(value);
    case "pct":
      return fmtPct(value);
    case "pct0":
      return value === null || value === void 0 ? "\u2014" : `${value.toFixed(0)}%`;
    case "ratio":
      return fmtNum(value, 2);
    case "score":
      return fmtNum(value, 0);
    default:
      return fmtNum(value);
  }
};
function Logo({ uri, symbol, enabled: enabled2 }) {
  const [failed, setFailed] = useState2(false);
  return <View2 style={styles2.logoBox}>
      {!enabled2 || !uri || failed ? <Text2 style={styles2.logoLetter}>{symbol.slice(0, 1)}</Text2> : <Image
    source={{ uri }}
    style={styles2.logo}
    resizeMode="contain"
    onError={() => setFailed(true)}
  />}
    </View2>;
}
function TickerRow({ ticker, position, sort, settings, starred, onPress, onToggleStar }) {
  const metricIsCap = sort.format === "cap";
  const metricValue = metricIsCap ? ticker.changePct : sort.value(ticker);
  const metricColour = metricIsCap || sort.format === "pct" ? tone(metricValue) : C.text;
  const shown = formatMetric(metricIsCap ? "pct" : sort.format, metricValue);
  return <Pressable2
    onPress={() => {
      tap();
      onPress(ticker);
    }}
    accessibilityRole="button"
    accessibilityLabel={`${ticker.symbol}, ${ticker.name}. ${fmtPrice(ticker.price)}, ${fmtPct(ticker.changePct)} today. ${sort.label} ${shown}.` + (position ? ` Rank ${position}.` : "") + (starred ? " On watchlist." : "")}
    style={({ pressed }) => [
      styles2.row,
      starred && styles2.rowStarred,
      pressed && styles2.rowPressed
    ]}
  >
      <Text2 style={styles2.position}>
        {position === null || position === void 0 ? "\u2014" : position}
      </Text2>

      <Logo uri={ticker.logo} symbol={ticker.symbol} enabled={settings.showLogos} />

      <View2 style={styles2.identity}>
        <Text2 style={styles2.symbol} numberOfLines={1}>{ticker.symbol}</Text2>
        <Text2 style={styles2.name} numberOfLines={1}>{ticker.name}</Text2>
      </View2>

      {settings.showSparklines && <View2 style={styles2.spark}>
          <Sparkline_default
    points={ticker.spark}
    color={(ticker.sparkChange ?? 0) >= 0 ? C.acid : C.down}
  />
        </View2>}

      <View2 style={styles2.numbers}>
        <Text2 style={styles2.price}>{fmtPrice(ticker.price)}</Text2>
        <Text2 style={[styles2.metric, { color: metricColour }]}>{shown}</Text2>
      </View2>

      {
    /* Nested inside the row's Pressable but claiming its own touches, so the
       star never opens the ticker and the row never toggles the watchlist.
       A bare glyph rather than a boxed control: repeated down a hundred rows
       a box is a lot of furniture for a binary. */
  }
      <Pressable2
    onPress={() => {
      (starred ? undo : confirm)();
      onToggleStar(ticker.symbol);
    }}
    hitSlop={slop(24)}
    accessibilityRole="button"
    accessibilityState={{ selected: starred }}
    accessibilityLabel={starred ? `Remove ${ticker.symbol} from watchlist` : `Add ${ticker.symbol} to watchlist`}
    style={({ pressed }) => [styles2.watch, pressed && styles2.watchPressed]}
  >
        <Text2 style={[styles2.watchGlyph, starred && styles2.watchGlyphOn]}>
          {starred ? "\u2605" : "\u2606"}
        </Text2>
      </Pressable2>
    </Pressable2>;
}
var styles2 = StyleSheet2.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    // Looser than it was: with the type a size larger, packing the maximum
    // number of rows onto the screen costs more in scanability than it buys.
    paddingVertical: 13,
    paddingRight: S.gutter - 2,
    paddingLeft: S.gutter - 2,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.lineSoft,
    // The edge is always present and usually invisible, so marking a row tints
    // it rather than nudging every column two pixels sideways.
    borderLeftWidth: 2,
    borderLeftColor: "transparent"
  },
  rowStarred: { borderLeftColor: C.acid, backgroundColor: "rgba(200,255,0,0.05)" },
  rowPressed: { backgroundColor: C.surface },
  position: { width: 30, color: C.faint, fontFamily: MONO, fontSize: T.micro },
  logoBox: {
    width: 30,
    height: 30,
    borderRadius: 7,
    backgroundColor: C.surfaceHi,
    borderWidth: S.hairline,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
    overflow: "hidden"
  },
  logo: { width: 22, height: 22 },
  logoLetter: { color: C.dim, fontFamily: MONO, fontSize: T.small },
  identity: { flex: 1, paddingRight: 8 },
  symbol: { color: C.text, fontFamily: MONO, fontSize: T.body, letterSpacing: 0.5 },
  name: { color: C.faint, fontSize: T.micro, marginTop: 3 },
  spark: { width: 54, marginRight: 10 },
  numbers: { alignItems: "flex-end", minWidth: 78 },
  price: { color: C.text, fontFamily: MONO, fontSize: T.body },
  metric: { fontFamily: MONO, fontSize: T.small, marginTop: 3 },
  watch: { paddingLeft: 12, alignItems: "center", justifyContent: "center" },
  watchPressed: { opacity: 0.5 },
  watchGlyph: { color: C.faint, fontSize: 19, lineHeight: 23 },
  watchGlyphOn: { color: C.acid }
});
var TickerRow_default = React3.memo(TickerRow);

// app/src/screens/RanksScreen.js
function RanksScreen({
  snapshot,
  tickers,
  index,
  universeKey,
  pendingKey,
  onSelectUniverse,
  settings,
  watchlist,
  staleMessage,
  onOpen,
  onToggleStar,
  onRefresh,
  refreshing,
  // Held by App rather than here, so opening a ticker or switching tabs does
  // not quietly reset the view the reader set up.
  listState,
  onListState,
  listRef
}) {
  const { sortKey, direction, query, sector, industry } = listState;
  const [universeOpen, setUniverseOpen] = useState3(false);
  const [cutOpen, setCutOpen] = useState3(false);
  const sort = sortByKey(sortKey);
  const bySector = snapshot.scope !== "sector";
  const cut = bySector ? sector : industry;
  const cutOptions = useMemo(
    () => bySector ? sectorOptions(tickers) : industryOptions(tickers),
    [bySector, tickers]
  );
  const rows = useMemo(
    () => arrange(tickers, { sortKey, query, sector, industry, direction }),
    [tickers, sortKey, query, sector, industry, direction]
  );
  const universes = useMemo(() => universeOptions(index), [index]);
  const switching = !!pendingKey && pendingKey !== universeKey;
  const switchingTo = switching ? findUniverse(index, pendingKey) : null;
  const bestFirst = direction === "desc";
  const filtered = cut !== "All" || !!query.trim();
  const pickSort = (key) => {
    if (key === sortKey) onListState({ direction: bestFirst ? "asc" : "desc" });
    else onListState({ sortKey: key, direction: "desc" });
  };
  return <View3 style={styles3.wrap}>
      {
    /* The universe is the first decision on this screen, so it heads it as a
       control rather than sitting in a settings list three taps away. */
  }
      <Pressable3
    onPress={() => {
      tick();
      setUniverseOpen(true);
    }}
    accessibilityRole="button"
    accessibilityLabel={`Universe, ${snapshot.title}, ${snapshot.universeSize} companies. Tap to change.`}
    style={({ pressed }) => [styles3.header, pressed && styles3.headerPressed]}
  >
        <View3 style={styles3.headerText}>
          <View3 style={styles3.titleRow}>
            <Text3 style={styles3.title} numberOfLines={1} accessibilityRole="header">
              {snapshot.title.toUpperCase()}
            </Text3>
            <Text3 style={styles3.caret}>▾</Text3>
            {switching && <ActivityIndicator2 size="small" color={C.acid} style={styles3.spinner} />}
          </View3>
          <Text3 style={styles3.subtitle} numberOfLines={1}>
            {switching && switchingTo ? `LOADING ${switchingTo.title.toUpperCase()}\u2026` : `${describeUniverse(snapshot)} \xB7 ${snapshot.dataDate}`}
          </Text3>
        </View3>
      </Pressable3>

      {!!staleMessage && <Banner text={staleMessage} />}

      <View3 style={styles3.filterRow}>
        <View3 style={styles3.searchWrap}>
          <TextInput
    value={query}
    onChangeText={(v) => onListState({ query: v })}
    placeholder="SEARCH SYMBOL OR NAME"
    placeholderTextColor={C.faint}
    autoCapitalize="characters"
    autoCorrect={false}
    accessibilityLabel="Search by symbol or company name"
    style={styles3.search}
  />
          {!!query && <Pressable3
    onPress={() => {
      tick();
      onListState({ query: "" });
    }}
    hitSlop={slop(26)}
    accessibilityRole="button"
    accessibilityLabel="Clear search"
    style={styles3.clear}
  >
              <Text3 style={styles3.clearMark}>×</Text3>
            </Pressable3>}
        </View3>
        <SelectButton
    label={cut === "All" ? bySector ? "ALL SECTORS" : "ALL INDUSTRIES" : cut.toUpperCase()}
    active={cut !== "All"}
    onPress={() => setCutOpen(true)}
    accessibilityLabel={`${bySector ? "Sector" : "Industry"} filter, ${cut === "All" ? "showing all" : cut}`}
  />
      </View3>

      <ChipRow accessibilityLabel="Sort by metric">
        {SORTS.map((s) => <Chip
    key={s.key}
    label={s.short}
    active={s.key === sortKey}
    onPress={() => pickSort(s.key)}
    accessibilityLabel={s.key === sortKey ? `${s.label}, sorted ${bestFirst ? "best first" : "worst first"}. Tap to reverse.` : `Sort by ${s.label}`}
  />)}
      </ChipRow>

      {
    /* The active metric spelled out, with its direction attached rather than
       floating in the header where it read as unrelated. */
  }
      <Pressable3
    onPress={() => {
      tick();
      onListState({ direction: bestFirst ? "asc" : "desc" });
    }}
    accessibilityRole="button"
    accessibilityLabel={`Sorted by ${sort.label}, ${bestFirst ? "best first" : "worst first"}. Tap to reverse.`}
    style={styles3.columns}
  >
        <Text3 style={styles3.colLeft}>#  TICKER</Text3>
        <Text3 style={styles3.colRight}>
          PRICE / <Text3 style={styles3.colMetric}>{sort.label}</Text3>
          <Text3 style={styles3.colDir}>{bestFirst ? "  \xB7 BEST FIRST \u25BC" : "  \xB7 WORST FIRST \u25B2"}</Text3>
        </Text3>
      </Pressable3>

      {filtered && <View3 style={styles3.summary}>
          <Text3 style={styles3.summaryText} numberOfLines={1}>
            {cut !== "All" ? cut : bySector ? "All sectors" : "All industries"}
            {query.trim() ? ` \xB7 \u201C${query.trim()}\u201D` : ""} · {rows.length}{" "}
            {rows.length === 1 ? "result" : "results"}
          </Text3>
          <Pressable3
    onPress={() => {
      tick();
      onListState({ query: "", sector: "All", industry: "All" });
    }}
    hitSlop={slop(30)}
    accessibilityRole="button"
    accessibilityLabel="Clear filters"
  >
            <Text3 style={styles3.summaryClear}>CLEAR</Text3>
          </Pressable3>
        </View3>}

      <FlatList
    ref={listRef}
    data={rows}
    keyExtractor={(t) => t.symbol}
    renderItem={({ item, index: i }) => <TickerRow_default
      ticker={item}
      position={item.ranks[sort.rank] ?? i + 1}
      sort={sort}
      settings={settings}
      starred={watchlist.includes(item.symbol)}
      onPress={onOpen}
      onToggleStar={onToggleStar}
    />}
    initialNumToRender={12}
    windowSize={9}
    removeClippedSubviews
    keyboardShouldPersistTaps="handled"
    keyboardDismissMode="on-drag"
    refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={C.acid} />}
    ListEmptyComponent={<Empty title="NO MATCHES" hint="Nothing in this universe matches that filter." />}
    contentContainerStyle={rows.length ? null : { flexGrow: 1 }}
  />

      <SelectSheet
    title="UNIVERSE"
    hint="Each list ranks its own members, so a company places differently against the whole market than against its sector."
    options={universes}
    value={universeKey}
    visible={universeOpen}
    onSelect={onSelectUniverse}
    onClose={() => setUniverseOpen(false)}
  />
      <SelectSheet
    title={bySector ? "FILTER BY SECTOR" : "FILTER BY INDUSTRY"}
    options={cutOptions}
    value={cut}
    visible={cutOpen}
    onSelect={(v) => onListState(bySector ? { sector: v } : { industry: v })}
    onClose={() => setCutOpen(false)}
  />
    </View3>;
}
var styles3 = StyleSheet3.create({
  wrap: { flex: 1 },
  header: { paddingHorizontal: S.gutter, paddingTop: 6, paddingBottom: 12, minHeight: S.tap },
  headerPressed: { opacity: 0.6 },
  headerText: { flexShrink: 1 },
  titleRow: { flexDirection: "row", alignItems: "center" },
  title: { color: C.text, fontFamily: MONO, fontSize: T.title, letterSpacing: 3, flexShrink: 1 },
  caret: { color: C.acid, fontFamily: MONO, fontSize: T.body, marginLeft: 8 },
  spinner: { marginLeft: 10 },
  subtitle: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.6, marginTop: 6 },
  filterRow: {
    flexDirection: "row",
    alignItems: "stretch",
    marginHorizontal: S.gutter,
    marginBottom: 10
  },
  searchWrap: { flex: 1, marginRight: 8, justifyContent: "center" },
  search: {
    paddingHorizontal: 12,
    paddingRight: 34,
    paddingVertical: 11,
    backgroundColor: C.surface,
    borderWidth: S.hairline,
    borderColor: C.line,
    borderRadius: S.radius,
    color: C.text,
    fontFamily: MONO,
    fontSize: T.small
  },
  clear: { position: "absolute", right: 10, height: 24, width: 24, alignItems: "center", justifyContent: "center" },
  clearMark: { color: C.dim, fontSize: 19, lineHeight: 22 },
  columns: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: S.gutter,
    paddingBottom: 8,
    paddingTop: 4,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.line
  },
  colLeft: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  colRight: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  colMetric: { color: C.text },
  colDir: { color: C.acid },
  summary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: S.gutter,
    paddingVertical: 9,
    backgroundColor: C.surface,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.line
  },
  summaryText: { color: C.dim, fontSize: T.micro, flexShrink: 1 },
  summaryClear: { color: C.acid, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1, paddingLeft: 12 }
});

// app/src/screens/SettingsScreen.js
import React5, { useState as useState4 } from "react";
import { Alert, ScrollView as ScrollView2, StyleSheet as StyleSheet4, Switch, Text as Text4, TextInput as TextInput2, View as View4 } from "react-native";
function Toggle({ label, hint, value, onChange }) {
  return <View4 style={styles4.toggleRow}>
      <View4 style={styles4.toggleText}>
        <Text4 style={styles4.toggleLabel}>{label}</Text4>
        {!!hint && <Text4 style={styles4.toggleHint}>{hint}</Text4>}
      </View4>
      <Switch
    value={value}
    onValueChange={onChange}
    accessibilityLabel={label}
    trackColor={{ false: C.line, true: C.acidDim }}
    thumbColor={value ? C.acid : C.faint}
    ios_backgroundColor={C.line}
  />
    </View4>;
}
function Fact({ label, value }) {
  return <View4 style={styles4.factRow}>
      <Text4 style={styles4.factKey}>{label}</Text4>
      <Text4 style={styles4.factValue}>{value}</Text4>
    </View4>;
}
function SettingsScreen({
  settings,
  onChange,
  snapshot,
  index,
  loadedCount,
  lastFetched,
  watchlistCount,
  onClearWatchlist,
  onResetAll,
  onRefresh,
  refreshing,
  refreshResult
}) {
  const [draftUrl, setDraftUrl] = useState4(settings.sourceUrl);
  const [sortOpen, setSortOpen] = useState4(false);
  const dirty = draftUrl.trim() !== settings.sourceUrl;
  const universes = index && index.universes || [];
  const applyUrl = () => {
    const url = draftUrl.trim();
    if (!/^https?:\/\//i.test(url)) {
      Alert.alert("Invalid URL", "The data URL must start with http:// or https://");
      return;
    }
    onChange({ sourceUrl: url });
    onRefresh(url);
  };
  const confirm2 = (title, message, action) => Alert.alert(title, message, [
    { text: "Cancel", style: "cancel" },
    { text: "Confirm", style: "destructive", onPress: action }
  ]);
  return <ScrollView2 style={styles4.wrap} contentContainerStyle={styles4.content} keyboardShouldPersistTaps="handled">
      <Text4 style={styles4.title} accessibilityRole="header">SETTINGS</Text4>

      <SectionTitle>DISPLAY</SectionTitle>
      <View4 style={styles4.selectRow}>
        <Text4 style={styles4.fieldLabel}>DEFAULT SORT ON OPEN</Text4>
        <SelectButton
    label={sortByKey(settings.defaultSort).label}
    onPress={() => setSortOpen(true)}
    accessibilityLabel={`Default sort, ${sortByKey(settings.defaultSort).label}`}
  />
      </View4>

      <Toggle
    label="Company logos"
    hint="Loaded from FMP's image CDN"
    value={settings.showLogos}
    onChange={(v) => onChange({ showLogos: v })}
  />
      <Toggle
    label="Row sparklines"
    hint="90-session trend beside each row"
    value={settings.showSparklines}
    onChange={(v) => onChange({ showSparklines: v })}
  />
      <Toggle
    label="Haptics"
    hint="Taps, chip selections and a tick per session while scrubbing a chart"
    value={settings.haptics}
    onChange={(v) => onChange({ haptics: v })}
  />
      <Toggle
    label="Refresh on open"
    hint="Otherwise the cached copy is used until you pull to refresh"
    value={settings.refreshOnOpen}
    onChange={(v) => onChange({ refreshOnOpen: v })}
  />

      <SectionTitle>DATA</SectionTitle>
      <Fact label="OPEN" value={`${snapshot?.title || "\u2014"} \xB7 ${snapshot?.universeSize ?? "\u2014"} tickers`} />
      <Fact label="DATA DATE" value={snapshot?.dataDate || "\u2014"} />
      <Fact
    label="BUILT"
    value={snapshot?.generatedAt?.replace("T", " ").replace("+00:00", " UTC") || "\u2014"}
  />
      <Fact label="SESSIONS" value={snapshot?.sessions ?? "\u2014"} />
      <Fact label="FETCHED" value={fmtWhen(lastFetched)} />
      <Fact
    label="UNIVERSES"
    value={`${universes.length} listed \xB7 ${loadedCount} on this phone`}
  />

      {
    /* The whole index in one place, so it is obvious what the picker on the
       Ranks screen is offering before you go looking for it. */
  }
      <Disclosure label="WHAT'S IN THE INDEX ›">
        {universes.map((u) => <Fact
    key={u.key}
    label={u.title.toUpperCase()}
    value={`${u.size} \xB7 ${u.file}`}
  />)}
        <Text4 style={styles4.hint}>
          Each file ranks its own members, so a company sits at one place in the Top 300 and another
          among its sector. Switch between them from the heading on the Ranks screen.
        </Text4>
      </Disclosure>

      <View4 style={styles4.actions}>
        <ActionButton
    label={refreshing ? "REFRESHING\u2026" : "REFRESH NOW"}
    busy={refreshing}
    onPress={() => onRefresh()}
  />
      </View4>
      {!!refreshResult && <View4 style={styles4.feedback}>
          <Banner text={refreshResult.message} tone={refreshResult.ok ? "ok" : "error"} />
        </View4>}

      <SectionTitle>STORAGE</SectionTitle>
      <Text4 style={styles4.hint}>
        The watchlist, these settings and every table you have opened live on this phone only. There
        is no account and no server holding any of it.
      </Text4>
      <View4 style={styles4.actions}>
        <ActionButton
    label={`CLEAR WATCHLIST (${watchlistCount})`}
    tone="danger"
    onPress={() => confirm2("Clear watchlist", `Remove all ${watchlistCount} tracked tickers?`, onClearWatchlist)}
  />
        <ActionButton
    label="RESET ALL DATA"
    tone="danger"
    onPress={() => confirm2("Reset everything", "Clear the watchlist, settings and every cached table?", onResetAll)}
  />
      </View4>

      {
    /* A raw GitHub URL is indispensable while working on the pipeline and
       irrelevant every other day, so it folds away rather than heading the
       screen. */
  }
      <Disclosure label="ADVANCED ›">
        <Text4 style={styles4.fieldLabel}>DATA DIRECTORY URL</Text4>
        <TextInput2
    value={draftUrl}
    onChangeText={setDraftUrl}
    autoCapitalize="none"
    autoCorrect={false}
    multiline
    placeholder={DEFAULT_SOURCE}
    placeholderTextColor={C.faint}
    accessibilityLabel="Data directory URL"
    style={styles4.input}
  />
        <View4 style={styles4.actions}>
          <ActionButton
    label={dirty ? "SAVE & REFRESH" : "SAVED"}
    busy={!dirty || refreshing}
    onPress={applyUrl}
  />
          <ActionButton
    label="RESET URL"
    onPress={() => {
      setDraftUrl(DEFAULT_SOURCE);
      onChange({ sourceUrl: DEFAULT_SOURCE });
      onRefresh(DEFAULT_SOURCE);
    }}
  />
        </View4>
        <Text4 style={styles4.hint}>
          A directory, not a file. The app reads index.json from it and then whichever file that
          index names, so any fork, branch or local server holding those two things works — point it
          somewhere and every universe in it appears in the picker. Nothing is saved until you tap
          save, and the result of the fetch is reported above.
        </Text4>
        <Fact label="SOURCE" value={snapshot?.source || "\u2014"} />
        <Fact label="FILE" value={snapshot?.scope === "sector" ? "sectors/\u2026json" : "snapshot.json"} />
      </Disclosure>

      <Text4 style={styles4.footnote}>
        Prices are dividend-adjusted daily closes from Financial Modeling Prep. The tables are
        rebuilt by hand rather than on a schedule, so the data date above is the one that counts —
        not today's. For information only, and not investment advice.
      </Text4>

      <SelectSheet
    title="DEFAULT SORT ON OPEN"
    options={sortOptions()}
    value={settings.defaultSort}
    visible={sortOpen}
    onSelect={(v) => onChange({ defaultSort: v })}
    onClose={() => setSortOpen(false)}
  />
    </ScrollView2>;
}
var styles4 = StyleSheet4.create({
  wrap: { flex: 1 },
  content: { paddingHorizontal: S.gutter, paddingBottom: 48, paddingTop: 6 },
  title: { color: C.text, fontFamily: MONO, fontSize: T.title, letterSpacing: 3 },
  selectRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.lineSoft
  },
  fieldLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  input: {
    marginTop: 10,
    padding: 12,
    backgroundColor: C.surface,
    borderWidth: S.hairline,
    borderColor: C.line,
    borderRadius: S.radius,
    color: C.acid,
    fontFamily: MONO,
    fontSize: T.micro,
    minHeight: 68
  },
  actions: { flexDirection: "row", flexWrap: "wrap", marginTop: 4 },
  feedback: { marginTop: 12, marginHorizontal: -S.gutter },
  hint: { color: C.faint, fontSize: T.micro, lineHeight: T.micro + 6, marginTop: 12 },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.lineSoft
  },
  toggleText: { flex: 1, paddingRight: 14 },
  toggleLabel: { color: C.text, fontSize: T.body },
  toggleHint: { color: C.faint, fontSize: T.micro, marginTop: 4, lineHeight: T.micro + 5 },
  factRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 9,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.lineSoft
  },
  factKey: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  factValue: { color: C.dim, fontFamily: MONO, fontSize: T.micro, flexShrink: 1, textAlign: "right" },
  footnote: {
    color: C.faint,
    fontSize: T.micro,
    lineHeight: T.micro + 6,
    marginTop: 28,
    borderTopWidth: S.hairline,
    borderTopColor: C.lineSoft,
    paddingTop: 14
  }
});

// app/src/screens/TickerScreen.js
import React7, { useMemo as useMemo3, useRef, useState as useState6 } from "react";
import { Image as Image2, Pressable as Pressable4, ScrollView as ScrollView3, StyleSheet as StyleSheet6, Text as Text6, View as View6 } from "react-native";

// app/src/components/PriceChart.js
import React6, { useMemo as useMemo2, useState as useState5 } from "react";
import { StyleSheet as StyleSheet5, Text as Text5, View as View5 } from "react-native";
var H = 200;
var PAD_TOP = 14;
var PAD_BOTTOM = 18;
function PriceChart({ points, showHint, onScrubbed }) {
  const [cursor, setCursor] = useState5(null);
  const [width, setWidth] = useState5(0);
  const geometry = useMemo2(() => {
    if (!points || points.length < 2 || width <= 0) return null;
    let min = Infinity;
    let max = -Infinity;
    for (const p of points) {
      if (p.close < min) min = p.close;
      if (p.close > max) max = p.close;
    }
    const span = max - min || Math.abs(max) * 0.02 || 1;
    const usable = H - PAD_TOP - PAD_BOTTOM;
    const step = width / (points.length - 1);
    const xy = points.map((p, i) => ({
      x: i * step,
      y: PAD_TOP + usable - (p.close - min) / span * usable
    }));
    const line = xy.map((c, i) => `${i === 0 ? "M" : "L"}${c.x.toFixed(2)} ${c.y.toFixed(2)}`).join(" ");
    const area = `${line} L${width} ${H - PAD_BOTTOM} L0 ${H - PAD_BOTTOM} Z`;
    return { min, max, xy, line, area, step };
  }, [points, width]);
  const rising = points && points.length > 1 && points[points.length - 1].close >= points[0].close;
  const stroke = rising ? C.acid : C.down;
  const onScrub = (evt) => {
    if (!geometry) return;
    const x = evt.nativeEvent.locationX;
    const index = Math.max(0, Math.min(points.length - 1, Math.round(x / geometry.step)));
    setCursor((previous) => {
      if (previous !== index) tick();
      return index;
    });
    if (onScrubbed) onScrubbed();
  };
  const active = cursor === null || !geometry ? null : points[cursor];
  return <View5 onLayout={(e) => setWidth(e.nativeEvent.layout.width)}>
      <View5 style={styles5.readout}>
        {active ? <>
            <Text5 style={styles5.readoutPrice}>{fmtPrice(active.close)}</Text5>
            <Text5 style={styles5.readoutDate}>{active.date}</Text5>
          </> : <>
            <Text5 style={styles5.readoutRange}>
              {geometry ? <>
                  <Text5 style={styles5.extremaKey}>LOW </Text5>
                  {fmtPrice(geometry.min)}
                  <Text5 style={styles5.extremaKey}>   HIGH </Text5>
                  {fmtPrice(geometry.max)}
                </> : ""}
            </Text5>
            <Text5 style={styles5.readoutDate}>{points ? `${points.length} sessions` : ""}</Text5>
          </>}
      </View5>

      <View5
    style={{ height: H }}
    accessibilityLabel={geometry ? `Price chart, ${points.length} sessions, low ${fmtPrice(geometry.min)}, high ${fmtPrice(geometry.max)}` : "Price chart unavailable"}
    onStartShouldSetResponder={() => true}
    onMoveShouldSetResponder={() => true}
    onResponderGrant={onScrub}
    onResponderMove={onScrub}
    onResponderRelease={() => setCursor(null)}
    onResponderTerminate={() => setCursor(null)}
  >
        {geometry ? <Default width={width} height={H}>
            <Defs>
              <LinearGradient id="fade" x1="0" y1="0" x2="0" y2="1">
                <Stop offset="0" stopColor={stroke} stopOpacity="0.22" />
                <Stop offset="1" stopColor={stroke} stopOpacity="0" />
              </LinearGradient>
            </Defs>

            <Line x1="0" y1={H - PAD_BOTTOM} x2={width} y2={H - PAD_BOTTOM} stroke={C.line} strokeWidth="1" />
            <Path d={geometry.area} fill="url(#fade)" />
            <Path d={geometry.line} fill="none" stroke={stroke} strokeWidth="1.8" strokeLinejoin="round" strokeLinecap="round" />

            {active && <>
                <Line
    x1={geometry.xy[cursor].x}
    y1={PAD_TOP - 8}
    x2={geometry.xy[cursor].x}
    y2={H - PAD_BOTTOM}
    stroke={C.dim}
    strokeWidth="1"
  />
                <Circle cx={geometry.xy[cursor].x} cy={geometry.xy[cursor].y} r="4.5" fill={stroke} />
              </>}
          </Default> : <View5 style={styles5.empty}>
            <Text5 style={styles5.emptyText}>NOT ENOUGH HISTORY</Text5>
          </View5>}

        {
    /* Shown until the reader scrubs their first chart, then never again --
       an affordance nobody discovers is the same as one that is missing. */
  }
        {geometry && showHint && !active && <View5 pointerEvents="none" style={styles5.hint}>
            <Text5 style={styles5.hintText}>DRAG TO INSPECT</Text5>
          </View5>}
      </View5>

      {geometry && <View5 style={styles5.axis}>
          <Text5 style={styles5.axisText}>{points[0].date}</Text5>
          <Text5 style={styles5.axisText}>{points[points.length - 1].date}</Text5>
        </View5>}
    </View5>;
}
var styles5 = StyleSheet5.create({
  readout: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 6
  },
  readoutPrice: { color: C.text, fontFamily: MONO, fontSize: T.large },
  readoutRange: { color: C.text, fontFamily: MONO, fontSize: T.micro },
  extremaKey: { color: C.faint },
  readoutDate: { color: C.faint, fontFamily: MONO, fontSize: T.micro },
  axis: { flexDirection: "row", justifyContent: "space-between", marginTop: 6 },
  axisText: { color: C.faint, fontFamily: MONO, fontSize: T.micro },
  empty: { flex: 1, alignItems: "center", justifyContent: "center" },
  emptyText: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1 },
  hint: { position: "absolute", top: 8, left: 0, right: 0, alignItems: "center" },
  hintText: {
    color: C.dim,
    fontFamily: MONO,
    fontSize: T.micro,
    letterSpacing: 1.6,
    backgroundColor: "rgba(20,21,24,0.85)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    overflow: "hidden"
  }
});

// app/src/screens/TickerScreen.js
var RETURN_ROWS = [
  ["1w", "1 WEEK"],
  ["1m", "1 MONTH"],
  ["3m", "3 MONTH"],
  ["6m", "6 MONTH"],
  ["ytd", "YTD"],
  ["1y", "1 YEAR"],
  ["2y", "2 YEAR"]
];
var MOMENTUM_ROWS = [
  ["3m", "3 MONTH"],
  ["6m", "6 MONTH"],
  ["9m", "9 MONTH"],
  ["12m", "12 MONTH"]
];
var EDGE = 28;
var SWIPE = 60;
function TickerScreen({
  ticker,
  snapshot,
  starred,
  onBack,
  onToggleStar,
  hintScrub,
  onScrubbed
}) {
  const [range, setRange] = useState6("1Y");
  const swipeStart = useRef(0);
  const scope = universeLabel(snapshot);
  const skip = snapshot.skip || {};
  const returnSkips = skip.returns || {};
  const momentumSkips = skip.momentum || (snapshot.momentum || {}).skips || {};
  const anySkip = Object.values(returnSkips).some((n) => n > 0);
  const sessions = (RANGES.find((r) => r.key === range) || RANGES[4]).sessions;
  const points = useMemo3(
    () => seriesFor(ticker, snapshot.dates, sessions),
    [ticker, snapshot.dates, sessions]
  );
  const rangeChange = useMemo3(() => changeOver(points), [points]);
  const suffix = (key) => returnSkips[key] > 0 ? ` \u2212${returnSkips[key]}D` : "";
  return <View6 style={styles6.wrap}>
      {
    /* An edge swipe back, because reaching for a control in the top-left
       corner one-handed is exactly what iOS taught people not to do. */
  }
      <View6
    style={styles6.edge}
    onStartShouldSetResponder={() => true}
    onResponderGrant={(e) => {
      swipeStart.current = e.nativeEvent.pageX;
    }}
    onResponderRelease={(e) => {
      if (e.nativeEvent.pageX - swipeStart.current > SWIPE) onBack();
    }}
  />

      <ScrollView3 style={styles6.scroll} contentContainerStyle={styles6.content}>
        <View6 style={styles6.topBar}>
          <Pressable4 onPress={onBack} hitSlop={slop(30)} accessibilityRole="button" accessibilityLabel="Back to list">
            <Text6 style={styles6.back}>‹ BACK</Text6>
          </Pressable4>
          <Pressable4
    onPress={() => {
      (starred ? undo : confirm)();
      onToggleStar(ticker.symbol);
    }}
    hitSlop={slop(30)}
    accessibilityRole="button"
    accessibilityState={{ selected: starred }}
    accessibilityLabel={starred ? "Remove from watchlist" : "Add to watchlist"}
  >
            <Text6 style={[styles6.watch, starred && styles6.watching]}>
              {starred ? "\u2605 WATCHING" : "\u2606 WATCH"}
            </Text6>
          </Pressable4>
        </View6>

        <View6 style={styles6.identity}>
          {!!ticker.logo && <View6 style={styles6.logoBox}>
              <Image2 source={{ uri: ticker.logo }} style={styles6.logo} resizeMode="contain" />
            </View6>}
          <View6 style={styles6.identityText}>
            <Text6 style={styles6.symbol} accessibilityRole="header">{ticker.symbol}</Text6>
            <Text6 style={styles6.name} numberOfLines={2}>{ticker.name}</Text6>
          </View6>
        </View6>

        <Text6 style={styles6.meta}>
          {ticker.sector.toUpperCase()}
          {ticker.industry ? ` \xB7 ${ticker.industry.toUpperCase()}` : ""} · {ticker.exchange}
        </Text6>

        <View6 style={styles6.priceBlock}>
          <View6>
            <Text6 style={styles6.price}>{fmtPrice(ticker.price)}</Text6>
            <Text6 style={[styles6.change, { color: tone(ticker.changePct) }]}>
              {ticker.change >= 0 ? "+" : ""}{fmtNum(ticker.change)} ({fmtPct(ticker.changePct)})
            </Text6>
          </View6>
          {
    /* A size, not a ranking -- so it belongs with the company, not in a
       section that is otherwise nothing but #n placings. */
  }
          <View6 style={styles6.capBlock}>
            <Text6 style={styles6.capLabel}>MARKET CAP</Text6>
            <Text6 style={styles6.capValue}>{fmtCap(ticker.marketCap)}</Text6>
          </View6>
        </View6>

        <ChipRow accessibilityLabel="Chart range">
          {RANGES.map((r) => <Chip
    key={r.key}
    compact
    label={r.key}
    active={r.key === range}
    onPress={() => setRange(r.key)}
    accessibilityLabel={`${r.key} chart range`}
  />)}
        </ChipRow>

        <View6 style={styles6.chartHead}>
          <Text6 style={styles6.chartLabel}>{range} CHANGE</Text6>
          <Text6 style={[styles6.chartChange, { color: tone(rangeChange) }]}>{fmtPct(rangeChange)}</Text6>
        </View6>

        <PriceChart points={points} showHint={hintScrub} onScrubbed={onScrubbed} />

        <SectionTitle>RETURNS</SectionTitle>
        <View6 style={styles6.grid}>
          {RETURN_ROWS.map(([key, label]) => <Stat
    key={key}
    label={`${label}${suffix(key)}`}
    value={fmtPct(ticker.returns[key])}
    color={tone(ticker.returns[key])}
    reason={missingReason(key)}
  />)}
        </View6>
        {anySkip && <Text6 style={styles6.note}>
            −nD means the window stops n sessions short of today. Short-term moves tend to reverse
            rather than persist, so every window long enough to afford it leaves its most recent
            stretch out — the same rule everywhere, scaled to each window's length.
          </Text6>}

        <SectionTitle>RISK</SectionTitle>
        <View6 style={styles6.grid}>
          <Stat label="VOL 30D" value={fmtMagnitude(ticker.volatility["30d"])} reason={missingReason("30d")} />
          <Stat label="VOL 90D" value={fmtMagnitude(ticker.volatility["90d"])} reason={missingReason("90d")} />
          <Stat label="VOL 1Y" value={fmtMagnitude(ticker.volatility["1y"])} reason={missingReason("1y")} />
          <Stat
    label="MAX DD 1Y"
    value={fmtMagnitude(ticker.maxDrawdown1y)}
    color={ticker.maxDrawdown1y === null ? void 0 : C.down}
    reason={missingReason("maxDrawdown")}
  />
          <Stat label="RETURN/RISK" value={fmtNum(ticker.riskAdjusted1y, 2)} reason={missingReason("riskAdjusted")} />
        </View6>

        <Disclosure label="HOW RISK IS MEASURED ›">
          <Text6 style={styles6.prose}>
            Volatility is the standard deviation of daily log returns over the window, annualised.
            It is a magnitude, not a direction — 30% means the price typically moves that much in a
            year either way, which is why it carries no sign.
          </Text6>
          <Text6 style={styles6.prose}>
            Max drawdown is the deepest peak-to-trough fall within the last year, measured on closing
            prices. It answers what holding through the worst stretch would have felt like, which an
            annual return on its own hides.
          </Text6>
          <Text6 style={styles6.prose}>
            Return/risk divides the 1-year return by 1-year volatility: how much movement was
            rewarded per unit of movement endured. There is no risk-free rate in it, so it compares
            these tickers against each other rather than being a Sharpe ratio.
          </Text6>
        </Disclosure>

        <SectionTitle>MOMENTUM</SectionTitle>
        <View6 style={styles6.grid}>
          <Stat
    label="SCORE"
    value={fmtNum(ticker.momentumScore, 0)}
    color={C.acid}
    width="50%"
    reason={missingReason("momentum")}
  />
          <Stat
    label={`RANK IN ${scope}`}
    value={fmtRank(ticker.ranks.momentum)}
    width="50%"
    reason={missingReason("momentum")}
  />
        </View6>

        {
    /* The windows the score is built from, with the skip stated on each
       rather than left to the disclosure. */
  }
        <View6 style={styles6.windows}>
          <View6 style={styles6.windowHead}>
            <Text6 style={styles6.windowHeadText}>WINDOW</Text6>
            <Text6 style={styles6.windowHeadText}>SKIPPED</Text6>
            <Text6 style={[styles6.windowHeadText, styles6.windowHeadRight]}>RETURN</Text6>
          </View6>
          {MOMENTUM_ROWS.map(([key, label]) => {
    const s = momentumSkips[key];
    const value = (ticker.momentumReturns || {})[key];
    return <View6 key={key} style={styles6.windowRow}>
                <Text6 style={styles6.windowLabel}>{label}</Text6>
                <Text6 style={styles6.windowSkip}>
                  {s === void 0 ? "\u2014" : s === 0 ? "none" : `last ${s}d`}
                </Text6>
                <Text6 style={[styles6.windowValue, { color: tone(value) }]}>{fmtPct(value)}</Text6>
              </View6>;
  })}
        </View6>

        <Disclosure label="HOW MOMENTUM WORKS ›">
          <Text6 style={styles6.prose}>
            Four returns are measured for every company: 3, 6, 9 and 12 months, each stopping short
            of today rather than running to the last close.
          </Text6>
          <Text6 style={styles6.prose}>
            The skip scales with the window at 20 sessions per 250, so the 12-month figure leaves out
            the last 20 sessions and the 3-month one only the last 5. A single fixed month would take
            a twelfth off the yearly window but a third off the quarterly one — a far heavier hand on
            the short end than the long.
          </Text6>
          <Text6 style={styles6.prose}>
            This ticker is ranked against the other {snapshot.universeSize - 1} in {snapshot.title}{" "}
            on each of those four windows, and the four placings are averaged and rescaled so 100 is
            the strongest of the {snapshot.universeSize}. A high score means winning across every
            timeframe, not spiking in one.
          </Text6>
          <Text6 style={styles6.prose}>
            Every table scores itself, so the same company carries a different score in the Top 300
            than it does among its own sector — the field it is being measured against is not the
            same field.
          </Text6>
          <Text6 style={styles6.prose}>
            It stays blank until a company has traded about 13 months — the 12-month window plus the
            skipped one. Scoring on whichever windows happened to exist would be a different measure
            wearing the same name.
          </Text6>
        </Disclosure>

        <SectionTitle>RANK IN {scope}</SectionTitle>
        <View6 style={styles6.grid}>
          <Stat label="MARKET CAP" value={fmtRank(ticker.ranks.marketCap)} color={C.acid} />
          <Stat label="1 MONTH" value={fmtRank(ticker.ranks.return_1m)} />
          <Stat label="3 MONTH" value={fmtRank(ticker.ranks.return_3m)} />
          <Stat label="6 MONTH" value={fmtRank(ticker.ranks.return_6m)} />
          <Stat label="YTD" value={fmtRank(ticker.ranks.return_ytd)} />
          <Stat label="1 YEAR" value={fmtRank(ticker.ranks.return_1y)} />
          <Stat label="RETURN/RISK" value={fmtRank(ticker.ranks.riskAdjusted)} />
          <Stat label="LOW VOL" value={fmtRank(ticker.ranks.volatility)} />
        </View6>

        <Text6 style={styles6.note}>
          Placings run 1 to {snapshot.universeSize} within {snapshot.title}
          {snapshot.scope === "sector" ? " \u2014 this company against its own sector, not the whole market." : "."}
        </Text6>

        <Text6 style={styles6.footnote}>
          Dividend-adjusted closes, {ticker.firstSession} to {ticker.asOf}.
        </Text6>
      </ScrollView3>
    </View6>;
}
var styles6 = StyleSheet6.create({
  wrap: { flex: 1 },
  scroll: { flex: 1 },
  content: { paddingHorizontal: S.gutter, paddingBottom: 44 },
  edge: { position: "absolute", left: 0, top: 0, bottom: 0, width: EDGE, zIndex: 5 },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 6,
    paddingBottom: 16
  },
  back: { color: C.dim, fontFamily: MONO, fontSize: T.small, letterSpacing: 1 },
  watch: { color: C.dim, fontFamily: MONO, fontSize: T.small, letterSpacing: 1 },
  watching: { color: C.acid },
  identity: { flexDirection: "row", alignItems: "center" },
  logoBox: {
    width: 46,
    height: 46,
    borderRadius: 9,
    backgroundColor: C.surfaceHi,
    borderWidth: S.hairline,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
    overflow: "hidden"
  },
  logo: { width: 34, height: 34 },
  identityText: { flex: 1 },
  symbol: { color: C.text, fontFamily: MONO, fontSize: 26, letterSpacing: 2 },
  name: { color: C.dim, fontSize: T.body, marginTop: 4 },
  meta: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.6, marginTop: 11 },
  priceBlock: {
    marginTop: 18,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between"
  },
  price: { color: C.text, fontFamily: MONO, fontSize: T.display },
  change: { fontFamily: MONO, fontSize: T.body, marginTop: 5 },
  capBlock: { alignItems: "flex-end", paddingBottom: 4 },
  capLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.6 },
  capValue: { color: C.text, fontFamily: MONO, fontSize: T.large, marginTop: 4 },
  chartHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline" },
  chartLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1.2 },
  chartChange: { fontFamily: MONO, fontSize: T.body },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: S.hairline,
    borderTopColor: C.line,
    paddingTop: 4,
    marginTop: 8
  },
  note: { color: C.faint, fontSize: T.micro, lineHeight: T.micro + 6, marginTop: 10 },
  prose: { color: C.dim, fontSize: T.small, lineHeight: T.small + 7, marginBottom: 11 },
  windows: { marginTop: 12, borderTopWidth: S.hairline, borderTopColor: C.line },
  windowHead: { flexDirection: "row", alignItems: "center", paddingTop: 10, paddingBottom: 4 },
  windowHeadText: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8, flex: 1 },
  windowHeadRight: { textAlign: "right" },
  windowRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    borderTopWidth: S.hairline,
    borderTopColor: C.lineSoft
  },
  windowLabel: { color: C.dim, fontFamily: MONO, fontSize: T.small, flex: 1 },
  windowSkip: { color: C.faint, fontFamily: MONO, fontSize: T.small, flex: 1 },
  windowValue: { fontFamily: MONO, fontSize: T.body, flex: 1, textAlign: "right" },
  footnote: {
    color: C.faint,
    fontSize: T.micro,
    lineHeight: T.micro + 5,
    marginTop: 26,
    borderTopWidth: S.hairline,
    borderTopColor: C.lineSoft,
    paddingTop: 12
  }
});

// app/src/screens/WatchlistScreen.js
import React8, { useMemo as useMemo4 } from "react";
import { FlatList as FlatList2, RefreshControl as RefreshControl2, StyleSheet as StyleSheet7, Text as Text7, View as View7 } from "react-native";
function WatchlistScreen({
  tickers,
  pending,
  settings,
  onOpen,
  onToggleStar,
  onRefresh,
  refreshing,
  listState,
  onListState,
  listRef
}) {
  const { sortKey } = listState;
  const rows = useMemo4(() => arrange(tickers, { sortKey, direction: "desc" }), [tickers, sortKey]);
  const average = useMemo4(() => {
    if (!tickers.length) return null;
    return tickers.reduce((sum, t) => sum + (t.changePct || 0), 0) / tickers.length;
  }, [tickers]);
  const sort = sortByKey(sortKey);
  return <View7 style={styles7.wrap}>
      <View7 style={styles7.header}>
        <View7 style={styles7.headerText}>
          <Text7 style={styles7.title} accessibilityRole="header">WATCHLIST</Text7>
          <Text7 style={styles7.subtitle}>
            {tickers.length} {tickers.length === 1 ? "TICKER" : "TICKERS"} TRACKED
            {pending > 0 ? ` \xB7 LOADING ${pending} MORE` : ""}
          </Text7>
        </View7>
        {average !== null && <View7
    style={styles7.avgBox}
    accessibilityLabel={`Equal weight average move today, ${fmtPct(average)}`}
  >
            <Text7 style={styles7.avgLabel}>EQUAL-WEIGHT AVG 1D</Text7>
            <Text7 style={[styles7.avgValue, { color: tone(average) }]}>{fmtPct(average)}</Text7>
          </View7>}
      </View7>

      {tickers.length > 0 && <ChipRow accessibilityLabel="Sort watchlist by metric">
          {SORTS.map((s) => <Chip
    key={s.key}
    label={s.short}
    active={s.key === sortKey}
    onPress={() => onListState({ sortKey: s.key })}
    accessibilityLabel={s.key === sortKey ? `${s.label}, selected` : `Sort by ${s.label}`}
  />)}
        </ChipRow>}

      {tickers.length > 0 && // The numbers down the left are places within this list. A rank carried
  // over from a table would be meaningless here: these names come from
  // whichever universes they were starred in, and #4 of the Top 300 sits
  // beside #4 of a hundred utilities without the two being comparable.
  <View7 style={styles7.columns}>
          <Text7 style={styles7.colLeft}>#  IN THIS LIST</Text7>
          <Text7 style={styles7.colRight}>
            PRICE / <Text7 style={styles7.colMetric}>{sort.label}</Text7>
          </Text7>
        </View7>}

      <FlatList2
    ref={listRef}
    data={rows}
    keyExtractor={(t) => t.symbol}
    renderItem={({ item, index }) => <TickerRow_default
      ticker={item}
      position={index + 1}
      sort={sort}
      settings={settings}
      starred
      onPress={onOpen}
      onToggleStar={onToggleStar}
    />}
    refreshControl={<RefreshControl2 refreshing={refreshing} onRefresh={onRefresh} tintColor={C.acid} />}
    ListEmptyComponent={<Empty
      title="NOTHING TRACKED YET"
      hint="Tap the star beside any row on the Ranks screen, or open a ticker and tap WATCH. Stars from every universe land here together."
    />}
    contentContainerStyle={rows.length ? null : { flexGrow: 1 }}
  />
    </View7>;
}
var styles7 = StyleSheet7.create({
  wrap: { flex: 1 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: S.gutter,
    paddingTop: 6,
    paddingBottom: 14
  },
  headerText: { flexShrink: 1, paddingRight: 12 },
  title: { color: C.text, fontFamily: MONO, fontSize: T.title, letterSpacing: 3 },
  subtitle: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8, marginTop: 6 },
  avgBox: { alignItems: "flex-end" },
  avgLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.6 },
  avgValue: { fontFamily: MONO, fontSize: T.large, marginTop: 4 },
  columns: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: S.gutter,
    paddingBottom: 8,
    paddingTop: 4,
    borderBottomWidth: S.hairline,
    borderBottomColor: C.line
  },
  colLeft: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  colRight: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 0.8 },
  colMetric: { color: C.text }
});

// app/App.js
var TABS = [
  { key: "ranks", label: "RANKS" },
  { key: "watchlist", label: "WATCH" },
  { key: "settings", label: "SETTINGS" }
];
var SPARK_SESSIONS = 90;
var SPARK_POINTS = 24;
var FEEDBACK_MS = 6e3;
var UNDO_MS = 6e3;
var decorate = (table) => table.tickers.map((t) => {
  const points = seriesFor(t, table.dates, SPARK_SESSIONS);
  return { ...t, spark: downsample(points, SPARK_POINTS), sparkChange: changeOver(points) };
});
function App() {
  const [ready, setReady] = useState7(false);
  const [settings, setSettings] = useState7(DEFAULT_SETTINGS);
  const [watchlist, setWatchlist] = useState7([]);
  const [index, setIndex] = useState7(null);
  const [tables, setTables] = useState7({});
  const [pendingKey, setPendingKey] = useState7(null);
  const [tab, setTab] = useState7("ranks");
  const [openSymbol, setOpenSymbol] = useState7(null);
  const [refreshing, setRefreshing] = useState7(false);
  const [notice, setNotice] = useState7(null);
  const [fatal, setFatal] = useState7(null);
  const [lastFetched, setLastFetched] = useState7(null);
  const [refreshResult, setRefreshResult] = useState7(null);
  const [undoItem, setUndoItem] = useState7(null);
  const [ranksState, setRanksState] = useState7({
    sortKey: DEFAULT_SETTINGS.defaultSort,
    direction: "desc",
    query: "",
    sector: "All",
    industry: "All"
  });
  const [watchState, setWatchState] = useState7({ sortKey: "change" });
  const ranksList = useRef2(null);
  const watchList = useRef2(null);
  const settingsRef = useRef2(settings);
  settingsRef.current = settings;
  const skipHydrate = useRef2(/* @__PURE__ */ new Set());
  const patchRanks = useCallback((p) => setRanksState((prev) => ({ ...prev, ...p })), []);
  const patchWatch = useCallback((p) => setWatchState((prev) => ({ ...prev, ...p })), []);
  const universeKey = settings.universeKey;
  const snapshot = tables[universeKey] || null;
  useEffect(() => {
    setHapticsEnabled(settings.haptics);
  }, [settings.haptics]);
  useEffect(() => {
    if (!refreshResult) return void 0;
    const timer = setTimeout(() => setRefreshResult(null), FEEDBACK_MS);
    return () => clearTimeout(timer);
  }, [refreshResult]);
  useEffect(() => {
    if (!undoItem) return void 0;
    const timer = setTimeout(() => setUndoItem(null), UNDO_MS);
    return () => clearTimeout(timer);
  }, [undoItem]);
  const store = useCallback((key, table) => {
    setTables((prev) => ({ ...prev, [key]: table }));
  }, []);
  const refresh = useCallback(async (urlOverride) => {
    const url = typeof urlOverride === "string" ? urlOverride : settingsRef.current.sourceUrl;
    setRefreshing(true);
    try {
      const listing = await fetchIndex(url);
      setIndex(listing.index);
      const wanted = settingsRef.current.universeKey;
      const universe = findUniverse(listing.index, wanted);
      if (!universe) throw new Error("That source lists no universes");
      const result = await fetchUniverse(url, universe);
      store(universe.key, result.table);
      if (universe.key !== wanted) {
        setSettings((prev) => {
          const next = { ...prev, universeKey: universe.key };
          saveSettings(next);
          return next;
        });
      }
      setFatal(null);
      setNotice(
        result.fromCache ? `OFFLINE \u2014 SHOWING CACHED ${result.table.dataDate} (${result.error})` : null
      );
      if (result.fetchedAt) setLastFetched(new Date(result.fetchedAt).toISOString());
      setRefreshResult(
        result.fromCache ? { ok: false, message: `Could not reach the source (${result.error}). Showing the cached ${result.table.dataDate} copy of ${result.table.title}.` } : { ok: true, message: `Updated just now \u2014 ${result.table.title}, ${result.table.universeSize} tickers, data date ${result.table.dataDate}.` }
      );
    } catch (err) {
      setFatal(err.message || "Could not load the data");
      setRefreshResult({ ok: false, message: err.message || "Could not load the data." });
    } finally {
      setRefreshing(false);
    }
  }, [store]);
  useEffect(() => {
    (async () => {
      const [storedSettings, storedWatchlist, cachedIndex] = await Promise.all([
        loadSettings(),
        loadWatchlist(),
        loadCachedIndex()
      ]);
      setSettings(storedSettings);
      setWatchlist(storedWatchlist);
      patchRanks({ sortKey: storedSettings.defaultSort });
      if (cachedIndex) setIndex(cachedIndex);
      const cachedTable = await loadCachedUniverse(storedSettings.universeKey);
      if (cachedTable) store(storedSettings.universeKey, cachedTable);
      setReady(true);
      if (storedSettings.refreshOnOpen || !cachedTable) await refresh();
    })();
  }, [refresh, patchRanks, store]);
  const updateSettings = useCallback((patch) => {
    setSettings((prev) => {
      const next = { ...prev, ...patch };
      saveSettings(next);
      return next;
    });
    if (patch.defaultSort) patchRanks({ sortKey: patch.defaultSort, direction: "desc" });
  }, [patchRanks]);
  const selectUniverse = useCallback(async (key) => {
    if (key === settingsRef.current.universeKey) return;
    const universe = findUniverse(index, key);
    if (!universe) return;
    const url = settingsRef.current.sourceUrl;
    const commit = () => {
      updateSettings({ universeKey: key });
      patchRanks({ sector: "All", industry: "All" });
      if (ranksList.current) ranksList.current.scrollToOffset({ offset: 0, animated: false });
    };
    setPendingKey(key);
    try {
      if (!tables[key]) {
        const cached = await loadCachedUniverse(key);
        if (cached) {
          store(key, cached);
          commit();
        }
      }
      const result = await fetchUniverse(url, universe);
      store(key, result.table);
      commit();
      setNotice(
        result.fromCache ? `OFFLINE \u2014 SHOWING CACHED ${result.table.dataDate} (${result.error})` : null
      );
      if (result.fetchedAt) setLastFetched(new Date(result.fetchedAt).toISOString());
    } catch (err) {
      setRefreshResult({ ok: false, message: `Could not load ${universe.title} (${err.message}).` });
    } finally {
      setPendingKey(null);
    }
  }, [index, tables, store, updateSettings, patchRanks]);
  useEffect(() => {
    if (!ready || !index || !watchlist.length) return;
    const have = /* @__PURE__ */ new Set();
    for (const table of Object.values(tables)) {
      for (const t of table.tickers) have.add(t.symbol);
    }
    if (watchlist.every((s) => have.has(s))) return;
    const next = index.universes.find((u) => !tables[u.key] && !skipHydrate.current.has(u.key));
    if (!next) return;
    let live = true;
    (async () => {
      try {
        const result = await fetchUniverse(settingsRef.current.sourceUrl, next);
        if (live) store(next.key, result.table);
      } catch (err) {
        skipHydrate.current.add(next.key);
      }
    })();
    return () => {
      live = false;
    };
  }, [ready, index, watchlist, tables, store]);
  const toggleStar = useCallback((symbol) => {
    setWatchlist((prev) => {
      const removing = prev.includes(symbol);
      const next = removing ? prev.filter((s) => s !== symbol) : [...prev, symbol];
      saveWatchlist(next);
      setUndoItem(removing ? symbol : null);
      return next;
    });
  }, []);
  const undoRemove = useCallback(() => {
    if (!undoItem) return;
    setWatchlist((prev) => {
      const next = prev.includes(undoItem) ? prev : [...prev, undoItem];
      saveWatchlist(next);
      return next;
    });
    setUndoItem(null);
  }, [undoItem]);
  const clearWatchlist = useCallback(() => {
    setWatchlist([]);
    saveWatchlist([]);
    setUndoItem(null);
  }, []);
  const resetAll = useCallback(async () => {
    await clearAll();
    setWatchlist([]);
    setTables({});
    setSettings(DEFAULT_SETTINGS);
    skipHydrate.current = /* @__PURE__ */ new Set();
    await refresh(DEFAULT_SETTINGS.sourceUrl);
  }, [refresh]);
  const markScrubbed = useCallback(() => {
    if (!settingsRef.current.hasScrubbed) updateSettings({ hasScrubbed: true });
  }, [updateSettings]);
  const tickers = useMemo5(() => snapshot ? decorate(snapshot) : [], [snapshot]);
  const watchTickers = useMemo5(() => {
    if (!watchlist.length) return [];
    const wanted = new Set(watchlist);
    const found = /* @__PURE__ */ new Map();
    const order = [
      ...Object.keys(tables).filter((k) => k !== universeKey),
      ...tables[universeKey] ? [universeKey] : []
    ];
    for (const key of order) {
      const table = tables[key];
      for (const t of table.tickers) {
        if (wanted.has(t.symbol)) found.set(t.symbol, { table, ticker: t });
      }
    }
    return Array.from(found.values()).map(({ table, ticker }) => {
      const points = seriesFor(ticker, table.dates, SPARK_SESSIONS);
      return { ...ticker, spark: downsample(points, SPARK_POINTS), sparkChange: changeOver(points) };
    });
  }, [watchlist, tables, universeKey]);
  const openTicker = useMemo5(() => {
    if (!openSymbol) return null;
    const here = tickers.find((t) => t.symbol === openSymbol);
    if (here) return { ticker: here, table: snapshot };
    const other = watchTickers.find((t) => t.symbol === openSymbol);
    if (!other) return null;
    const table = Object.values(tables).find((tb) => tb.tickers.some((t) => t.symbol === openSymbol));
    return table ? { ticker: other, table } : null;
  }, [openSymbol, tickers, snapshot, watchTickers, tables]);
  const onTab = (key) => {
    if (key === tab) {
      const list = key === "ranks" ? ranksList.current : key === "watchlist" ? watchList.current : null;
      if (list) {
        tick();
        list.scrollToOffset({ offset: 0, animated: true });
      }
      return;
    }
    tick();
    setTab(key);
  };
  if (!ready || !snapshot && !fatal) {
    return <SafeAreaView style={styles8.app}>
        <StatusBar barStyle="light-content" />
        <Loading label="FETCHING DATA" />
      </SafeAreaView>;
  }
  if (!snapshot && fatal) {
    return <SafeAreaView style={styles8.app}>
        <StatusBar barStyle="light-content" />
        <View8 style={styles8.fatal}>
          <Text8 style={styles8.fatalTitle} accessibilityRole="header">NO DATA</Text8>
          <Text8 style={styles8.fatalText}>{fatal}</Text8>
          <Text8 style={styles8.fatalHint}>Check the data URL under Settings, then try again.</Text8>
          <View8 style={styles8.fatalActions}>
            <ActionButton label={refreshing ? "RETRYING\u2026" : "RETRY"} busy={refreshing} onPress={() => refresh()} />
            <ActionButton label="OPEN SETTINGS" onPress={() => {
      setFatal(null);
      setTab("settings");
    }} />
          </View8>
        </View8>
      </SafeAreaView>;
  }
  const shared = {
    settings,
    watchlist,
    onOpen: (t) => setOpenSymbol(t.symbol),
    onToggleStar: toggleStar,
    onRefresh: refresh,
    refreshing
  };
  return <SafeAreaView style={styles8.app}>
      <StatusBar barStyle="light-content" />

      {
    /* Every tab stays mounted and inactive ones are merely hidden.
       Unmounting them would throw away scroll position and filters. */
  }
      <View8 style={styles8.body}>
        <View8 style={tab === "ranks" ? styles8.pane : styles8.paneHidden}>
          <RanksScreen
    snapshot={snapshot}
    tickers={tickers}
    index={index}
    universeKey={universeKey}
    pendingKey={pendingKey}
    onSelectUniverse={selectUniverse}
    staleMessage={notice}
    listState={ranksState}
    onListState={patchRanks}
    listRef={ranksList}
    {...shared}
  />
        </View8>
        <View8 style={tab === "watchlist" ? styles8.pane : styles8.paneHidden}>
          <WatchlistScreen
    tickers={watchTickers}
    pending={watchlist.length - watchTickers.length}
    listState={watchState}
    onListState={patchWatch}
    listRef={watchList}
    {...shared}
  />
        </View8>
        <View8 style={tab === "settings" ? styles8.pane : styles8.paneHidden}>
          <SettingsScreen
    settings={settings}
    onChange={updateSettings}
    snapshot={snapshot}
    index={index}
    loadedCount={Object.keys(tables).length}
    lastFetched={lastFetched}
    watchlistCount={watchlist.length}
    onClearWatchlist={clearWatchlist}
    onResetAll={resetAll}
    onRefresh={refresh}
    refreshing={refreshing}
    refreshResult={refreshResult}
  />
        </View8>

        {
    /* Over the panes but inside the body, so the tab bar stays reachable
       and the list underneath keeps its place. */
  }
        {openTicker && <View8 style={styles8.overlay}>
            <TickerScreen
    ticker={openTicker.ticker}
    snapshot={openTicker.table}
    starred={watchlist.includes(openTicker.ticker.symbol)}
    onBack={() => setOpenSymbol(null)}
    onToggleStar={toggleStar}
    hintScrub={!settings.hasScrubbed}
    onScrubbed={markScrubbed}
  />
          </View8>}
      </View8>

      {tab !== "ranks" && !!notice && <Banner text={notice} />}

      {!!undoItem && <Snackbar
    text={`${undoItem} removed from watchlist`}
    actionLabel="UNDO"
    onAction={undoRemove}
  />}

      <View8 style={styles8.tabBar} accessibilityRole="tablist">
        {TABS.map((t) => {
    const active = t.key === tab;
    return <Pressable5
      key={t.key}
      style={styles8.tab}
      onPress={() => onTab(t.key)}
      accessibilityRole="tab"
      accessibilityState={{ selected: active }}
      accessibilityLabel={t.key === "watchlist" && watchlist.length ? `Watch, ${watchlist.length} tracked` : t.label}
    >
              <View8 style={[styles8.tabMark, active && styles8.tabMarkActive]} />
              <Text8 style={[styles8.tabLabel, active && styles8.tabLabelActive]}>
                {t.label}
                {t.key === "watchlist" && watchlist.length ? ` ${watchlist.length}` : ""}
              </Text8>
            </Pressable5>;
  })}
      </View8>
    </SafeAreaView>;
}
var styles8 = StyleSheet8.create({
  app: { flex: 1, backgroundColor: C.bg },
  body: { flex: 1 },
  pane: { ...StyleSheet8.absoluteFillObject },
  paneHidden: { ...StyleSheet8.absoluteFillObject, display: "none" },
  overlay: { ...StyleSheet8.absoluteFillObject, backgroundColor: C.bg },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: S.hairline,
    borderTopColor: C.line,
    backgroundColor: C.surface
  },
  // A full 44pt target even though the label is small.
  tab: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: S.tap, paddingVertical: 8 },
  tabMark: { width: 18, height: 2, backgroundColor: "transparent", marginBottom: 7 },
  tabMarkActive: { backgroundColor: C.acid },
  tabLabel: { color: C.faint, fontFamily: MONO, fontSize: T.micro, letterSpacing: 1.4 },
  tabLabelActive: { color: C.acid },
  fatal: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 34 },
  fatalTitle: { color: C.text, fontFamily: MONO, fontSize: T.large, letterSpacing: 2 },
  fatalText: { color: C.down, fontFamily: MONO, fontSize: T.small, marginTop: 14, textAlign: "center" },
  fatalHint: { color: C.faint, fontSize: T.small, marginTop: 16, textAlign: "center", lineHeight: 19 },
  fatalActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", marginTop: 18 }
});
export {
  App as default
};
