#!/usr/bin/env bash
#
# Bundle app/ into a single self-contained app/snack/App.js.
#
# Snack's `sourceUrl` parameter loads one file, which makes for a URL of a few
# hundred characters instead of the ~3.5 KB needed to list every module. The
# generated file is a build artifact -- edit app/src/, never app/snack/.
#
# Usage:
#   scripts/bundle_snack.sh [--data-branch BRANCH]
#
# --data-branch repoints the bundled snapshot URL at a branch, for previewing
# before the app's branch has merged into main.

set -euo pipefail
cd "$(dirname "$0")/.."

DATA_BRANCH=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --data-branch) DATA_BRANCH="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

OUT="app/snack/App.js"
mkdir -p "$(dirname "$OUT")"

# JSX is preserved rather than lowered to createElement calls, so the file
# stays readable if someone opens it in the Snack editor.
npx --yes esbuild app/App.js \
  --bundle \
  --format=esm \
  --jsx=preserve \
  --loader:.js=jsx \
  --external:react \
  --external:react-native \
  --external:react-native-svg \
  --external:@react-native-async-storage/async-storage \
  --external:expo-haptics \
  --banner:js='// GENERATED by scripts/bundle_snack.sh -- do not edit.
// Source of truth is app/App.js and app/src/. Regenerate after any change.' \
  --outfile="$OUT"

if [[ -n "$DATA_BRANCH" ]]; then
  python3 - "$OUT" "$DATA_BRANCH" <<'PY'
import re, sys
path, branch = sys.argv[1], sys.argv[2]
src = open(path).read()
pinned = (
    "https://raw.githubusercontent.com/vandyckmed-droid/thisone/"
    f"refs/heads/{branch}/data/"
)
src, n = re.subn(
    r"https://raw\.githubusercontent\.com/vandyckmed-droid/thisone/[^']*?/data/",
    pinned, src)
if n != 1:
    sys.exit(f"expected exactly one data URL in the bundle, found {n}")
open(path, "w").write(src)
print(f"Pinned data directory to {branch}")
PY
fi

printf 'Wrote %s (%s)\n' "$OUT" "$(du -h "$OUT" | cut -f1)"
